# Configuration for Rasa NLU pipeline
language: "en"
pipeline:
  - name: "WhitespaceTokenizer"
  - name: "RegexFeaturizer"
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: "CountVectorsFeaturizer"
  - name: "EmbeddingIntentClassifier"

# Configuration for Rasa Core policies
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
  - name: RulePolicy
  - name: MappingPolicy
